spring:
  application:
   name : Glorious
   

  data:
    mongodb:
      uri: mongodb+srv://glorious:gopal@glorius-education.yjagxwu.mongodb.net/?appName=glorius-education 
      database: school  
logging:
  level:
    root: WARN
    in.glorious: INFO
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.security: WARN
    org.mongodb.driver: ERROR

server:
  port: ${PORT:8080}